services:
  - type: web
    name: blog-app-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
