services:
  - type: web
    name: blog-app-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DB_NAME
        fromDatabase:
          name: blog-app-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: blog-app-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: blog-app-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: blog-app-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: blog-app-db
          property: port
      - key: CORS_ALLOWED_ORIGINS
        value: "*"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: blog-app-db
    databaseName: blogapp
    user: blogapp
    plan: free 