# Generated by Django 5.0.1 on 2025-07-25 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢'), ('angry', '😠'), ('fire', '🔥'), ('rocket', '🚀'), ('eyes', '👀'), ('clap', '👏'), ('pray', '🙏'), ('muscle', '💪'), ('brain', '🧠'), ('heart_eyes', '😍'), ('sunglasses', '😎'), ('party', '🎉'), ('star', '⭐'), ('thumbs_up', '👍'), ('thumbs_down', '👎'), ('check', '✅')], help_text='Type of reaction', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
