# Generated by Django 5.0.1 on 2025-07-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_initial'),
    ]

    operations = [
    ]
