# Generated by Django 5.0.1 on 2025-07-27 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='postview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'user'), name='unique_post_user_view'),
        ),
        migrations.AddConstraint(
            model_name='postview',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('post', 'session_key'), name='unique_post_session_view'),
        ),
    ]
